<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <?= $this->headMeta(); ?>
    <?= $this->headTitle('Rollun')->setSeparator(' - ')->setAutoEscape(false) ?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
<style>
    html, body {
        width: 100%;
        height: 100%;
        background-color: lightgray;
    }
    .r-event-sidebar {

    }
    .r-content-container {
        font-size: 0.8rem;
        width: 1200px;
        background-color: #fff;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    }
    .r-content-column {
        min-height: fit-content;
    }
    .r-column-label {
        margin: 1.5rem 0.25rem 0.75rem 0.25rem;
        text-align: center;
        font-weight: 500;
        line-height: 1.2;
        font-size: 1.125rem;
    }

</style>
<?php $this->rootPage = function () {
    return '#';
};?>
<body>
<nav id='navbar' class="navbar navbar-dark bg-dark navbar-fixed-top">
    <a class="navbar-brand" href="#">
        <img src="http://rollun.com/assets/img/logo.jpg" style="max-height: 1.5rem; margin-left: 1em"></a>
    <div class="navbar-nav justify-content-center" id="r-nav-dropdowns"></div>
    <div class="navbar-form navbar-right">
        <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fas fa-search"></i>
                </div>
            </div>
            <input type="text" class="form-control form-control-sm" placeholder="Найти страницу" style="min-width: 15rem">
        </div>
    </div>
</nav>
<?= $this->inlineScript() ?>
<div class="container-fluid p-0 r-content-container" id="r-content-container">
    <div class="row m-0">
        <div class="col-md-2 sidebar p-1 r-nav-list" id="r-nav-list">
            <div class="r-column-label">МЕНЮ</div>
        </div>
        <div class="col-md-8 main px-2 py-1 border-right border-left r-content-column" id="r-content-column">
            <div class="r-column-label" style="font-size: 1.5rem">ТЕСТОВАЯ СТРАНИЦА</div>
            <?php echo $this->content ?>
        </div>
        <div class="col-md-2 p-1 r-event-sidebar">
            <div class="r-column-label">УВЕДОМЛЕНИЯ</div>
            <div class="card mb-1">
                <div class="mb-1 px-1 card-title bg-info">
                    <div>
                        Уведомление
                        <i class="fas fa-times" style="position: relative; float: right; margin: 2px; color: white;"></i>
                    </div>
                </div>
                <div class="card-body p-1">
                    <p class="card-text">Здесь в ближайшем будущем появятся системные уведомления, еееее! </p>
                </div>
            </div>
            <div class="card mb-1">
                <div class="mb-1 px-1 card-title bg-danger">
                    <div>
                        Критическая ошибка
                        <i class="fas fa-times" style="position: relative; float: right; margin: 2px; color: white;"></i>
                    </div>
                </div>
                <div class="card-body p-1">
                    <p class="card-text">CСообщение о критической ошибке</p>
                </div>
            </div>
            <div class="card mb-1">
                <div class="mb-1 px-1 card-title bg-warning">
                    <div>
                        Ошибка
                        <i class="fas fa-times" style="position: relative; float: right; margin: 2px; color: white;"></i>
                    </div>
                </div>
                <div class="card-body p-1">
                    <p class="card-text">Сообщение об ошибке</p>
                </div>
            </div>
            <div class="card mb-1">
                <div class="mb-1 px-1 card-title bg-success">
                    <div>
                        Успех
                        <i class="fas fa-times" style="position: relative; float: right; margin: 2px; color: white;"></i>
                    </div>
                </div>
                <div class="card-body p-1">
                    <p class="card-text">Сообщение об успехе</p>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>