<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <?= $this->headMeta(); ?>
    <?= $this->headTitle('Rollun')->setSeparator(' - ')->setAutoEscape(false) ?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
<style>
    .r-event-sidebar {
        overflow-y: scroll;
    }

    .r-content-container {
        font-size: 0.8rem;
        width: 1200px;
        background-color: #fff;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    }

    .r-content-column {
        height: -webkit-fill-available;
        min-height: fit-content;
    }

</style>
<?php $this->rootPage = function () {
    return '#';
};?>
<body style="max-width: 100%; max-height: 100%; background-color: lightgray;">
<nav class="navbar navbar-dark bg-dark navbar-fixed-top">
    <a class="navbar-brand" href="#">Rollun</a>
    <div class="navbar-nav mr-auto" id="r-nav-dropdowns"></div>
    <div class="navbar-form navbar-right">
        <div class="input-group">
            <div class="input-group-prepend">
                <i class="input-group-text fas fa-search"></i>
            </div>
            <input type="text" class="form-control" placeholder="Найти страницу" style="min-width: 15rem">
        </div>
    </div>
</nav>

<div class="container-fluid p-0 r-content-container" id="r-content-container">
    <div class="row m-0">
        <div class="col-md-2 sidebar p-1 r-nav-list" id="r-nav-list">
            <?= $this->lsb(); ?>
        </div>
        <div class="col-md-8 main p-1 border-right border-left r-content-column">
            <?php echo $this->content ?>
        </div>
        <div class="col-md-2 p-1 r-event-sidebar">
            <div class="card p-1 m-1">
                <div class="card-body p-1">
                    <p class="card-text">Здесь в ближайшем будущем появятся системные уведомления, еееее! </p>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->inlineScript() ?>
</body>
</html>