<?php
$paramsString = json_encode($this->navigationParams);
?>
<h1>Контент</h1>
<script>
	require([
		'dojo/dom-class',
		'dojo/_base/window',
		'dojo/dom',
		'rgrid/NavPanes'
	], function (domClass,
				 window,
				 dom,
				 NavPanes,
	) {
		domClass.add(window.body(), 'flat');
		const testPanesLayout = JSON.parse('<?= $paramsString?>'),
			navPanes = new NavPanes({layoutConfig: testPanesLayout});
		navPanes.placeAt(dom.byId('r-nav-list'));
	})
</script>
<div id='some-content'></div>
<?php $this->dojo()->setDebug(true);
$this->dojo()->addLoader(); ?>
<?php $this->addTopNavbarContent();?>
<?php $this->addLeftNavbarContent(); ?>


