<link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.3.1/css/all.css'>
<style>
    body {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    @media (max-width: 700px) {
        body {
            align-items: start;
        }
    }

    .login-container {
        max-width: 20rem;
        min-width: 300px;
        padding: 1rem;
    }

    .login-form {
        display: flex;
        flex-direction: column;
    }
</style>
<div class="text-center m-2 login-container">
    <img src="http://rollun.com/assets/img/logo.jpg" class="m-3 mb-4">
    <form class="login-form pt-1">
        <a href="" class="btn btn-primary m-1">Login with Google account</a>
        <a href="" class="btn btn-secondary m-1">Register</a>
    </form>
    <p id='copyright' class="text-muted"></p>
    <script>
		const currentYear = (new Date()).getFullYear();
		document.getElementById('copyright').innerText = '© 2014-'+currentYear;
    </script>
</div>